-- 데이터베이스 생성 및 선택
CREATE DATABASE IF NOT EXISTS ssaveryTime
    DEFAULT CHARACTER SET utf8mb4
    COLLATE utf8mb4_general_ci;
USE ssaveryTime;

DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS LIKES;
DROP TABLE IF EXISTS SCRAP;
DROP TABLE IF EXISTS AI_TOKEN;
DROP TABLE IF EXISTS MENU;
DROP TABLE IF EXISTS STAR;
DROP TABLE IF EXISTS BOARD;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS RESTAURANT;

-- 1. 테이블 생성
CREATE TABLE USER (
    USER_ID    INT    NOT NULL AUTO_INCREMENT,
    USERNAME    VARCHAR(255)    NOT NULL UNIQUE,
    PASSWORD    VARCHAR(255)    NOT NULL,
    NAME    VARCHAR(100)    NOT NULL,
    ROLE    ENUM('USER', 'ADMIN')    NOT NULL DEFAULT 'USER',
    SEASON    INT    NULL,
    BAEKJOON    VARCHAR(100) NULL,
    VALID ENUM('1', '0') NOT NULL,
    CREATED_AT    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID)
);
CREATE TABLE BOARD (
    BOARD_ID    INT    NOT NULL AUTO_INCREMENT,
    USER_ID    INT    NOT NULL,
    TITLE    VARCHAR(255)    NOT NULL,
    BODY    TEXT    NULL,
    VISIBLE    ENUM('1', '0')    NOT NULL DEFAULT '1',
    WARNING_CNT    INT    NOT NULL DEFAULT 0,
    CREATED_AT    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (BOARD_ID)
);
CREATE TABLE COMMENT (
    COMMENT_ID    INT    NOT NULL AUTO_INCREMENT,
    BOARD_ID    INT    NOT NULL,
    USER_ID    INT    NOT NULL,
    BODY    VARCHAR(500)    NOT NULL,
    VISIBLE    ENUM('1', '0')    NOT NULL DEFAULT '1',
    WARNING_CNT    INT    NOT NULL DEFAULT 0,
    CREATED_AT    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (COMMENT_ID)
);
CREATE TABLE LIKES (
    LIKES_ID    INT    NOT NULL AUTO_INCREMENT,
    BOARD_ID    INT    NOT NULL,
    USER_ID    INT    NOT NULL,
    PRIMARY KEY (LIKES_ID),
    UNIQUE KEY UK_LIKES_BOARD_USER (BOARD_ID, USER_ID)
);
CREATE TABLE SCRAP (
    SCRAP_ID    INT    NOT NULL AUTO_INCREMENT,
    USER_ID    INT    NOT NULL,
    BOARD_ID    INT    NOT NULL,
    PRIMARY KEY (SCRAP_ID),
    UNIQUE KEY UK_SCRAP_USER_BOARD (USER_ID, BOARD_ID)
);
CREATE TABLE AI_TOKEN (
    TOKEN_ID    INT    NOT NULL AUTO_INCREMENT,
    REST    INT    NOT NULL DEFAULT 0,
    LAST_UPDATE    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TOKEN_ID)
);
CREATE TABLE RESTAURANT (
    RESTAURANT_ID    INT    NOT NULL AUTO_INCREMENT,
    NAME    VARCHAR(255)    NOT NULL,
    PRIMARY KEY (RESTAURANT_ID)
);
CREATE TABLE MENU (
    MENU_ID    INT    NOT NULL AUTO_INCREMENT,
    RESTAURANT_ID    INT    NOT NULL,
    MENU    VARCHAR(255)    NOT NULL,
    DATE    DATETIME    NULL,
    PRIMARY KEY (MENU_ID)
);
CREATE TABLE STAR (
    STAR_ID    INT    NOT NULL AUTO_INCREMENT,
    USER_ID    INT    NOT NULL,
    RESTAURANT_ID    INT    NOT NULL,
    CATEGORY    ENUM('TASTE', 'AMOUNT')    NOT NULL,
    SCORE     INT     NOT NULL, -- 새로 추가된 컬럼
    DATE    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (STAR_ID)
);

-- 2. 외래 키 (FOREIGN KEY) 제약 조건 추가
ALTER TABLE BOARD ADD CONSTRAINT FK_USER_TO_BOARD FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID) ON DELETE CASCADE;
ALTER TABLE COMMENT ADD CONSTRAINT FK_BOARD_TO_COMMENT FOREIGN KEY (BOARD_ID) REFERENCES BOARD (BOARD_ID) ON DELETE CASCADE;
ALTER TABLE COMMENT ADD CONSTRAINT FK_USER_TO_COMMENT FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID) ON DELETE CASCADE;
ALTER TABLE LIKES ADD CONSTRAINT FK_BOARD_TO_LIKES FOREIGN KEY (BOARD_ID) REFERENCES BOARD (BOARD_ID) ON DELETE CASCADE;
ALTER TABLE LIKES ADD CONSTRAINT FK_USER_TO_LIKES FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID) ON DELETE CASCADE;
ALTER TABLE SCRAP ADD CONSTRAINT FK_USER_TO_SCRAP FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID) ON DELETE CASCADE;
ALTER TABLE SCRAP ADD CONSTRAINT FK_BOARD_TO_SCRAP FOREIGN KEY (BOARD_ID) REFERENCES BOARD (BOARD_ID) ON DELETE CASCADE;
ALTER TABLE MENU ADD CONSTRAINT FK_RESTAURANT_TO_MENU FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT (RESTAURANT_ID) ON DELETE CASCADE;
ALTER TABLE STAR ADD CONSTRAINT FK_USER_TO_STAR FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID) ON DELETE CASCADE;
ALTER TABLE STAR ADD CONSTRAINT FK_RESTAURANT_TO_STAR FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT (RESTAURANT_ID) ON DELETE CASCADE;


-- 3. 더미 데이터 삽입 (외래 키 순서 고려: USER -> RESTAURANT -> BOARD -> 나머지)

-- USER (USER_ID: 1 ~ 5)
INSERT INTO USER (USERNAME, PASSWORD, NAME, ROLE, SEASON, BAEKJOON, VALID) VALUES
('kinguser', 'hashed_pw_01', '유저왕', 'USER', 14, 'GOLD V', '1'),
('admin_guy', 'hashed_pw_admin', '최고관리자', 'ADMIN', NULL, NULL, '1'),
('season_2_user', 'hashed_pw_03', '계절이', 'USER', 13, 'SILVER III', '1'),
('temp_disabled', 'hashed_pw_04', '잠시휴식', 'USER', 15, 'PATINUM V', '0'),
('active_member', 'hashed_pw_05', '활동회원', 'USER', 15, 'BRONZE I', '1');

-- RESTAURANT (RESTAURANT_ID: 1 ~ 5)
INSERT INTO RESTAURANT (NAME) VALUES
('육수고집'),
('소담상'),
('더고메'),
('차이나호'),
('속이찬새참');

-- BOARD (BOARD_ID: 1 ~ 5, USER_ID: 1, 5, 3, 2, 1 사용)
INSERT INTO BOARD (USER_ID, TITLE, BODY, VISIBLE, WARNING_CNT) VALUES
(1, '백반집 점심 후기', '오늘 백반집 가봤는데 가성비 최고예요.', '1', 0),
(5, '이번 시즌 알고리즘 질문', '다들 백준 문제 푸시나요?', '1', 0),
(3, '솔직히 실버들은 발언 허락 받고 해야한다 생각합니다.', '광주캠퍼스 노트북 쓰기 좋은 카페 아시는 분?', '1', 0),
(2, '운영 공지: 서비스 업데이트 안내', '새로운 기능이 추가될 예정입니다.', '1', 0),
(1, '숨김 테스트 게시글', '이 글은 관리자가 숨길 수 있습니다.', '0', 0);

-- COMMENT (BOARD_ID: 1~5, USER_ID: 3, 5, 1, 5, 4 사용)
INSERT INTO COMMENT (BOARD_ID, USER_ID, BODY, VISIBLE, WARNING_CNT) VALUES
(1, 3, '메뉴가 궁금해요!', '1', 0),
(2, 5, '저는 요즘 DP 문제 풀고 있습니다.', '1', 0),
(3, 1, '프리미엄 로스터리 추천합니다.', '1', 0),
(4, 5, '업데이트 기대하겠습니다!', '1', 0),
(1, 4, '혼밥하기 괜찮은가요?', '1', 0);

-- LIKES (BOARD_ID, USER_ID 조합이 고유해야 함)
INSERT INTO LIKES (BOARD_ID, USER_ID) VALUES
(1, 5),
(2, 1),
(2, 3),
(3, 5),
(4, 1);

-- SCRAP (USER_ID, BOARD_ID 조합이 고유해야 함)
INSERT INTO SCRAP (USER_ID, BOARD_ID) VALUES
(5, 1),
(1, 3),
(3, 4),
(5, 4),
(2, 2);

-- AI_TOKEN
INSERT INTO AI_TOKEN (REST, LAST_UPDATE) VALUES
(10, DATE_SUB(NOW(), INTERVAL 3 HOUR));

-- MENU (RESTAURANT_ID: 1~5 사용)
INSERT INTO MENU (RESTAURANT_ID, MENU, DATE) VALUES
(1, '제육볶음 정식', '2025-11-07 12:00:00'),
(2, '클래식 치즈 버거', '2025-11-07 12:00:00'),
(3, '탄탄멘', '2025-11-07 12:00:00'),
(4, '에티오피아 예가체프', '2025-11-07 12:00:00'),
(5, '슈퍼 디럭스 피자', '2025-11-06 18:30:00');

-- STAR (SCORE 컬럼 추가 및 1~5점 임의 부여)
INSERT INTO STAR (USER_ID, RESTAURANT_ID, CATEGORY, SCORE) VALUES
(1, 1, 'TASTE', 5), -- user1이 백반집에 맛 별점 5점
(5, 1, 'AMOUNT', 4), -- user5가 백반집에 양 별점 4점
(3, 2, 'TASTE', 3), -- user3이 버거집에 맛 별점 3점
(1, 3, 'TASTE', 5), -- user1이 누들 팩토리에 맛 별점 5점
(5, 5, 'AMOUNT', 4); -- user5가 피자에 양 별점 4점